apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: rkalluru/frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
spec:
  containers:
    - name: cart
      image: rkalluru/cart
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
spec:
  containers:
    - name: shipping
      image: rkalluru/shipping
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
spec:
  containers:
    - name: catalogue
      image: rkalluru/catalogue
---
apiVersion: v1
kind: Pod
metadata:
  name: user
spec:
  containers:
    - name: user
      image: rkalluru/user
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
spec:
  containers:
    - name: payment
      image: rkalluru/payment
